Changed material column in eles.txt
While trying to run the example to start understanding the different parts of the software, I noticed an error :
  File "C:\Users\huetg\AppData\Local\Programs\Python\Python36\lib\site-packages\
solidspy\assemutil.py", line 114, in retriever
    par0, par1 = mats[im, :]
IndexError: index 1 is out of bounds for axis 0 with size 1

After further investigation, it was cause by the material being referenced as "1" giving the value "1" to "im" but the matrix "mats" has only one line, referenced as line 0.
Replacing the reference to the material from 1 to 0 gives the expected behavior.

The general rule is that the first line in mater.txt is material "0", the second material "1" and so on.